#! /bin/sh

# Colors - Pywal
. "${HOME}/.cache/wal/colors.sh"
bspc config focused_border_color "$color6"
bspc config normal_border_color  "$color5"
bspc config active_border_color  "$color2"
bspc config presel_feedback_color "$color2"

bspc monitor -d I II III IV V

bspc config border_width        3
bspc config top_padding         8 
bspc config right_padding       8
bspc config left_padding        8
bspc config bottom_padding      50 
bspc config window_gap          7 

bspc config split_ratio              0.60
bspc config borderless_monocle       false
bspc config gapless_monocle          false

bspc rule -a Firefox                 state=pseudo_tiled
bspc rule -a Gimp                    desktop='^4' state=floating follow=on
bspc rule -a Emacs                   state=tiled
bspc rule -a mplayer2                state=floating
bspc rule -a Kupfer.py               focus=on
bspc rule -a Screenkey               manage=off
bspc rule -a Lutris                  state=floating
bspc rule -a Deluge                  state=floating
bspc rule -a kitty                   state=tiled
bspc rule -a Zathura                 state=tiled
bspc rule -a Spotify                 state=monocle desktop='^5' follow=on
bspc rule -a "mpv"                   state=floating  rectangle=320x180
bspc rule -a Xournal                 state=tiled


pgrep -x sxhkd > /dev/null || sxhkd &
redshift -l 45.07049:7.68682 -m randr &
# blurwal &
# ~/.config/bspwm/borders &
