#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


# Colors - Pywal
. "${HOME}/.cache/wal/colors.sh"
bspc config focused_border_color "$background"
bspc config normal_border_color  "$background"
bspc config active_border_color  "$background"
bspc config presel_feedback_color "$color2"


bspc monitor -d I II III IV V

bspc config border_width        1
bspc config top_padding         0
bspc config right_padding       0
bspc config left_padding        0
bspc config bottom_padding      0
bspc config window_gap          0

bspc config split_ratio              0.60
bspc config borderless_monocle       false
bspc config gapless_monocle          false

bspc rule -a Gimp                    desktop='^4' state=floating follow=on
bspc rule -a Emacs                   state=tiled
bspc rule -a mplayer2                state=floating
bspc rule -a Kupfer.py               focus=on
bspc rule -a Screenkey               manage=off
bspc rule -a Lutris                  state=floating
bspc rule -a Deluge                  state=floating
bspc rule -a kitty                   state=tiled bspc rule -a Zathura                 state=pseudo_tiled
bspc rule -a Spotify                 state=tiled desktop='^5' follow=on
bspc rule -a "mpv"                     state=pseudo_tiled
bspc rule -a Xournal                 state=pseudo_tiled

# ~/.config/bspwm/borders &
# blurwal --backend feh &

